// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: envelope.proto

package goir

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	groupver "k8s.io/idl/ckdl-ir/goir/groupver"
	markers "k8s.io/idl/ckdl-ir/goir/markers"
	types "k8s.io/idl/ckdl-ir/goir/types"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GroupVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description *groupver.GroupVersion `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Kinds       []*types.Kind          `protobuf:"bytes,2,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Types       []*types.Subtype       `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *GroupVersion) Reset() {
	*x = GroupVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envelope_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupVersion) ProtoMessage() {}

func (x *GroupVersion) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupVersion.ProtoReflect.Descriptor instead.
func (*GroupVersion) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *GroupVersion) GetDescription() *groupver.GroupVersion {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *GroupVersion) GetKinds() []*types.Kind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *GroupVersion) GetTypes() []*types.Subtype {
	if x != nil {
		return x.Types
	}
	return nil
}

type MarkerSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package string               `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Markers []*markers.MarkerDef `protobuf:"bytes,2,rep,name=markers,proto3" json:"markers,omitempty"` // TODO: allow docs, attributes
}

func (x *MarkerSet) Reset() {
	*x = MarkerSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envelope_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkerSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerSet) ProtoMessage() {}

func (x *MarkerSet) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerSet.ProtoReflect.Descriptor instead.
func (*MarkerSet) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *MarkerSet) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *MarkerSet) GetMarkers() []*markers.MarkerDef {
	if x != nil {
		return x.Markers
	}
	return nil
}

type Partial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupVersions []*GroupVersion       `protobuf:"bytes,1,rep,name=group_versions,json=groupVersions,proto3" json:"group_versions,omitempty"`
	Dependencies  []*Partial_Dependency `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	SourceMap     []*Location           `protobuf:"bytes,3,rep,name=source_map,json=sourceMap,proto3" json:"source_map,omitempty"`
	MarkerSets    []*MarkerSet          `protobuf:"bytes,4,rep,name=marker_sets,json=markerSets,proto3" json:"marker_sets,omitempty"`
}

func (x *Partial) Reset() {
	*x = Partial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envelope_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partial) ProtoMessage() {}

func (x *Partial) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partial.ProtoReflect.Descriptor instead.
func (*Partial) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Partial) GetGroupVersions() []*GroupVersion {
	if x != nil {
		return x.GroupVersions
	}
	return nil
}

func (x *Partial) GetDependencies() []*Partial_Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Partial) GetSourceMap() []*Location {
	if x != nil {
		return x.SourceMap
	}
	return nil
}

func (x *Partial) GetMarkerSets() []*MarkerSet {
	if x != nil {
		return x.MarkerSets
	}
	return nil
}

type Bundle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualFiles []*Bundle_File `protobuf:"bytes,1,rep,name=virtual_files,json=virtualFiles,proto3" json:"virtual_files,omitempty"`
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envelope_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *Bundle) GetVirtualFiles() []*Bundle_File {
	if x != nil {
		return x.VirtualFiles
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path []int32 `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
	// start col, start row, end col, end row
	Span []int32 `protobuf:"varint,2,rep,packed,name=span,proto3" json:"span,omitempty"` // single field to get packend encoding
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envelope_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetPath() []int32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Location) GetSpan() []int32 {
	if x != nil {
		return x.Span
	}
	return nil
}

type Partial_Dependency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupVersion *types.GroupVersionRef `protobuf:"bytes,1,opt,name=group_version,json=groupVersion,proto3" json:"group_version,omitempty"`
	From         string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *Partial_Dependency) Reset() {
	*x = Partial_Dependency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envelope_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partial_Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partial_Dependency) ProtoMessage() {}

func (x *Partial_Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partial_Dependency.ProtoReflect.Descriptor instead.
func (*Partial_Dependency) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Partial_Dependency) GetGroupVersion() *types.GroupVersionRef {
	if x != nil {
		return x.GroupVersion
	}
	return nil
}

func (x *Partial_Dependency) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type Bundle_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Contents *Partial `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *Bundle_File) Reset() {
	*x = Bundle_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envelope_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bundle_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle_File) ProtoMessage() {}

func (x *Bundle_File) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle_File.ProtoReflect.Descriptor instead.
func (*Bundle_File) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Bundle_File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bundle_File) GetContents() *Partial {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_envelope_proto protoreflect.FileDescriptor

var file_envelope_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x1a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x0c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x62, 0x2e, 0x69,
	0x72, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x05, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x05, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x12, 0x2a, 0x0a,
	0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6b,
	0x62, 0x2e, 0x69, 0x72, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x74, 0x79,
	0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x59, 0x0a, 0x09, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x72, 0x53, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x12, 0x32, 0x0a, 0x07, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72,
	0x73, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x44, 0x65, 0x66, 0x52, 0x07, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x72, 0x73, 0x22, 0xcc, 0x02, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c,
	0x12, 0x3a, 0x0a, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3d, 0x0a, 0x0c,
	0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x61, 0x6c, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x0c, 0x64,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x31, 0x0a, 0x0b, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x53,
	0x65, 0x74, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x74, 0x73, 0x1a, 0x63,
	0x0a, 0x0a, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x41, 0x0a, 0x0d,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x66, 0x52, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x22, 0x89, 0x01, 0x0a, 0x06, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x37,
	0x0a, 0x0d, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x42, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x0c, 0x76, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x46, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x32, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x73,
	0x70, 0x61, 0x6e, 0x42, 0x19, 0x5a, 0x17, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x69, 0x64,
	0x6c, 0x2f, 0x63, 0x6b, 0x64, 0x6c, 0x2d, 0x69, 0x72, 0x2f, 0x67, 0x6f, 0x69, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData = file_envelope_proto_rawDesc
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(file_envelope_proto_rawDescData)
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_envelope_proto_goTypes = []interface{}{
	(*GroupVersion)(nil),          // 0: kb.ir.GroupVersion
	(*MarkerSet)(nil),             // 1: kb.ir.MarkerSet
	(*Partial)(nil),               // 2: kb.ir.Partial
	(*Bundle)(nil),                // 3: kb.ir.Bundle
	(*Location)(nil),              // 4: kb.ir.Location
	(*Partial_Dependency)(nil),    // 5: kb.ir.Partial.Dependency
	(*Bundle_File)(nil),           // 6: kb.ir.Bundle.File
	(*groupver.GroupVersion)(nil), // 7: kb.ir.groupver.GroupVersion
	(*types.Kind)(nil),            // 8: kb.ir.types.Kind
	(*types.Subtype)(nil),         // 9: kb.ir.types.Subtype
	(*markers.MarkerDef)(nil),     // 10: kb.ir.markers.MarkerDef
	(*types.GroupVersionRef)(nil), // 11: kb.ir.types.GroupVersionRef
}
var file_envelope_proto_depIdxs = []int32{
	7,  // 0: kb.ir.GroupVersion.description:type_name -> kb.ir.groupver.GroupVersion
	8,  // 1: kb.ir.GroupVersion.kinds:type_name -> kb.ir.types.Kind
	9,  // 2: kb.ir.GroupVersion.types:type_name -> kb.ir.types.Subtype
	10, // 3: kb.ir.MarkerSet.markers:type_name -> kb.ir.markers.MarkerDef
	0,  // 4: kb.ir.Partial.group_versions:type_name -> kb.ir.GroupVersion
	5,  // 5: kb.ir.Partial.dependencies:type_name -> kb.ir.Partial.Dependency
	4,  // 6: kb.ir.Partial.source_map:type_name -> kb.ir.Location
	1,  // 7: kb.ir.Partial.marker_sets:type_name -> kb.ir.MarkerSet
	6,  // 8: kb.ir.Bundle.virtual_files:type_name -> kb.ir.Bundle.File
	11, // 9: kb.ir.Partial.Dependency.group_version:type_name -> kb.ir.types.GroupVersionRef
	2,  // 10: kb.ir.Bundle.File.contents:type_name -> kb.ir.Partial
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_envelope_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envelope_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkerSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envelope_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envelope_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bundle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envelope_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envelope_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partial_Dependency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envelope_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bundle_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_envelope_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_rawDesc = nil
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
