// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: backend.proto

package backend

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Log_Level int32

const (
	Log_INFO  Log_Level = 0
	Log_ERROR Log_Level = 1
)

// Enum value maps for Log_Level.
var (
	Log_Level_name = map[int32]string{
		0: "INFO",
		1: "ERROR",
	}
	Log_Level_value = map[string]int32{
		"INFO":  0,
		"ERROR": 1,
	}
)

func (x Log_Level) Enum() *Log_Level {
	p := new(Log_Level)
	*p = x
	return p
}

func (x Log_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Log_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_proto_enumTypes[0].Descriptor()
}

func (Log_Level) Type() protoreflect.EnumType {
	return &file_backend_proto_enumTypes[0]
}

func (x Log_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Log_Level.Descriptor instead.
func (Log_Level) EnumDescriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1, 0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []*Response_File `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetFile() []*Response_File {
	if x != nil {
		return x.File
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lvl   Log_Level    `protobuf:"varint,1,opt,name=lvl,proto3,enum=kb.ir.backend.Log_Level" json:"lvl,omitempty"`
	Trace []*Log_Trace `protobuf:"bytes,2,rep,name=trace,proto3" json:"trace,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetLvl() Log_Level {
	if x != nil {
		return x.Lvl
	}
	return Log_INFO
}

func (x *Log) GetTrace() []*Log_Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type Response_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *Response_File) Reset() {
	*x = Response_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_File) ProtoMessage() {}

func (x *Response_File) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_File.ProtoReflect.Descriptor instead.
func (*Response_File) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Response_File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Response_File) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type Log_Trace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Values  []*Log_Trace_KeyValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Node    *Log_Trace_Node       `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *Log_Trace) Reset() {
	*x = Log_Trace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log_Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Trace) ProtoMessage() {}

func (x *Log_Trace) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Trace.ProtoReflect.Descriptor instead.
func (*Log_Trace) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Log_Trace) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Log_Trace) GetValues() []*Log_Trace_KeyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Log_Trace) GetNode() *Log_Trace_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type Log_Trace_KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are assignable to Value:
	//	*Log_Trace_KeyValue_Str
	//	*Log_Trace_KeyValue_OtherNode
	Value isLog_Trace_KeyValue_Value `protobuf_oneof:"value"`
}

func (x *Log_Trace_KeyValue) Reset() {
	*x = Log_Trace_KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log_Trace_KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Trace_KeyValue) ProtoMessage() {}

func (x *Log_Trace_KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Trace_KeyValue.ProtoReflect.Descriptor instead.
func (*Log_Trace_KeyValue) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Log_Trace_KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (m *Log_Trace_KeyValue) GetValue() isLog_Trace_KeyValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Log_Trace_KeyValue) GetStr() string {
	if x, ok := x.GetValue().(*Log_Trace_KeyValue_Str); ok {
		return x.Str
	}
	return ""
}

func (x *Log_Trace_KeyValue) GetOtherNode() *Log_Trace_Node {
	if x, ok := x.GetValue().(*Log_Trace_KeyValue_OtherNode); ok {
		return x.OtherNode
	}
	return nil
}

type isLog_Trace_KeyValue_Value interface {
	isLog_Trace_KeyValue_Value()
}

type Log_Trace_KeyValue_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

type Log_Trace_KeyValue_OtherNode struct {
	OtherNode *Log_Trace_Node `protobuf:"bytes,3,opt,name=other_node,json=otherNode,proto3,oneof"`
}

func (*Log_Trace_KeyValue_Str) isLog_Trace_KeyValue_Value() {}

func (*Log_Trace_KeyValue_OtherNode) isLog_Trace_KeyValue_Value() {}

type Log_Trace_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path []int32 `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
}

func (x *Log_Trace_Node) Reset() {
	*x = Log_Trace_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log_Trace_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Trace_Node) ProtoMessage() {}

func (x *Log_Trace_Node) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Trace_Node.ProtoReflect.Descriptor instead.
func (*Log_Trace_Node) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *Log_Trace_Node) GetPath() []int32 {
	if x != nil {
		return x.Path
	}
	return nil
}

var File_backend_proto protoreflect.FileDescriptor

var file_backend_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x22, 0x74,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x1a, 0x36, 0x0a, 0x04,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0xa8, 0x03, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x2a, 0x0a, 0x03,
	0x6c, 0x76, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6b, 0x62, 0x2e, 0x69,
	0x72, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x52, 0x03, 0x6c, 0x76, 0x6c, 0x12, 0x2e, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x1a, 0xa6, 0x02, 0x0a, 0x05, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b,
	0x62, 0x2e, 0x69, 0x72, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x4c, 0x6f, 0x67,
	0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x1a, 0x79, 0x0a, 0x08, 0x4b, 0x65,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x3e, 0x0a, 0x0a,
	0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6b, 0x62, 0x2e, 0x69, 0x72, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x48,
	0x00, 0x52, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x07, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1a, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x22, 0x1c, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e,
	0x46, 0x4f, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x42,
	0x21, 0x5a, 0x1f, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x69, 0x64, 0x6c, 0x2f, 0x63, 0x6b,
	0x64, 0x6c, 0x2d, 0x69, 0x72, 0x2f, 0x67, 0x6f, 0x69, 0x72, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_proto_rawDescOnce sync.Once
	file_backend_proto_rawDescData = file_backend_proto_rawDesc
)

func file_backend_proto_rawDescGZIP() []byte {
	file_backend_proto_rawDescOnce.Do(func() {
		file_backend_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_proto_rawDescData)
	})
	return file_backend_proto_rawDescData
}

var file_backend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_backend_proto_goTypes = []interface{}{
	(Log_Level)(0),             // 0: kb.ir.backend.Log.Level
	(*Response)(nil),           // 1: kb.ir.backend.Response
	(*Log)(nil),                // 2: kb.ir.backend.Log
	(*Response_File)(nil),      // 3: kb.ir.backend.Response.File
	(*Log_Trace)(nil),          // 4: kb.ir.backend.Log.Trace
	(*Log_Trace_KeyValue)(nil), // 5: kb.ir.backend.Log.Trace.KeyValue
	(*Log_Trace_Node)(nil),     // 6: kb.ir.backend.Log.Trace.Node
}
var file_backend_proto_depIdxs = []int32{
	3, // 0: kb.ir.backend.Response.file:type_name -> kb.ir.backend.Response.File
	0, // 1: kb.ir.backend.Log.lvl:type_name -> kb.ir.backend.Log.Level
	4, // 2: kb.ir.backend.Log.trace:type_name -> kb.ir.backend.Log.Trace
	5, // 3: kb.ir.backend.Log.Trace.values:type_name -> kb.ir.backend.Log.Trace.KeyValue
	6, // 4: kb.ir.backend.Log.Trace.node:type_name -> kb.ir.backend.Log.Trace.Node
	6, // 5: kb.ir.backend.Log.Trace.KeyValue.other_node:type_name -> kb.ir.backend.Log.Trace.Node
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_backend_proto_init() }
func file_backend_proto_init() {
	if File_backend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log_Trace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log_Trace_KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log_Trace_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_backend_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Log_Trace_KeyValue_Str)(nil),
		(*Log_Trace_KeyValue_OtherNode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_proto_goTypes,
		DependencyIndexes: file_backend_proto_depIdxs,
		EnumInfos:         file_backend_proto_enumTypes,
		MessageInfos:      file_backend_proto_msgTypes,
	}.Build()
	File_backend_proto = out.File
	file_backend_proto_rawDesc = nil
	file_backend_proto_goTypes = nil
	file_backend_proto_depIdxs = nil
}
