// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 The Kubernetes Authors

// Code generated by helpgen. DO NOT EDIT.

package go2ir

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (Generator) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "",
		DetailedHelp: markers.DetailedHelp{
			Summary: "generates (experimental) Kubernetes API intermediate representation protos.",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"AllowDangerousTypes": markers.DetailedHelp{
				Summary: "allows types which are usually omitted from CRD generation because they are not recommended. ",
				Details: "Currently the following additional types are allowed when this is true: float32 float64 \n Left unspecified, the default is false",
			},
		},
	}
}
